### ISSUE TITLE
Is this repo still being maintained?

### ISSUE THREAD

**Issue by ahnick** [weppos/whois-parser#134]
Hi, I noticed that this repo hasn't had any commits done to it for over a year.  Is it still being maintained? or is development happening elsewhere?

**Comment by weppos** [comment]
It is not discontinued, and the development is not happening elsewhere. I am not fully committed to this project though.

**Comment by pdfrod** [comment]
Any suggestion for users that still rely on this project and would like to see it brough up-to-date @weppos? Will you allow other maintainers to step in? Or should we just fork it?

**Comment by jarthod** [comment]
@pdfrod, this project isn't really maintained by @weppos any more, so I ended up starting [my fork](https://github.com/jarthod/whois-parser) in which I merged many of the pending PRs and implemented a lot of other fixes. I try to keep it maintained in hope it could be merged back upstream some day so everyone can benefit from it (without having to dig through issues and forks). But it's a been a couple years now so at some point I guess it'll make sense to consider the upstream merge unlikely and release an official new gem under a different name. I still hope to avoid that if possible, for the sake of the community.

If you need a more maintained version you can use my fork in the meantime:
```ruby
gem 'whois-parser', github: 'jarthod/whois-parser' # Unofficial but more up-to-date fork, check status at https://github.com/jarthod/whois-parser
```

Also if you want to help or have fixes to suggest you can open PR there, better not start yet another fork if possible.

**Comment by pdfrod** [comment]
Thanks for your message @jarthod. Yeah, I was trying to get a definitive answer from the mantainer if the project should be forked and released under a different name, or if there is any chance to revive this repo and continue with the same name. It's looking like the former is the more realistic scenario.

**Comment by jarthod** [comment]
Indeed 😔
