### ISSUE TITLE
Add whois.dot.ga parser

### ISSUE THREAD

**Issue by weppos** [weppos/whois-parser#16]
See https://github.com/weppos/whois/issues/494

**Comment by HugoPoi** [comment]
@weppos `.ga` TLD whois server change to `whois.my.ga` https://github.com/weppos/whois/blob/master/data/tld.json need an update.

**Comment by weppos** [comment]
It looks like .GA still doesn't provide an official whois host.
https://github.com/whois/ianawhois/blob/master/GA

@HugoPoi Do you have some official link where I can see `whois.my.ga` listed?
