### ISSUE TITLE
Place fixtures in tld subdirectory when using mkwhois.rb

### ISSUE THREAD

**Issue by mpchadwick** [weppos/whois-parser#2]
https://github.com/weppos/whois/pull/460#issuecomment-160642051 indicates that fixtures should go in a subdirectory for the corresponding TLD however `mkwhois.rb` is not doing that.

I'm assuming this fix should be targeted to this repo?

I can submit a patch for this when I have a moment.

**Comment by weppos** [comment]
> I'm assuming this fix should be targeted to this repo?

Yes, it's correct.

> I can submit a patch for this when I have a moment.

That would be great! :+1:
