### ISSUE TITLE
Registrar ID field for .au domains

### ISSUE THREAD

**Issue by afoster** [weppos/whois-parser#20]
Hi

It appears that, for .au domains, the "Registrar ID" field once made available by whois.audns.net.au is no longer returned, although a "Registrar Name" is.

I have submitted a support request with AusRegistry to ask if they can clarify, however it appears as though the field disappeared from auDA's WHOIS policy somewhere inbetween http://www.auda.org.au/policies/index-of-published-policies/2010/2010-06/ and the latest policy, http://www.auda.org.au/policies/index-of-published-policies/2014/2014-07/.

Currently the parser for whois.audns.net.au returns nil instead of a `Whois::Record::Registar` because it relies on an ID being present. However I think it's still useful to surface the registrar name somehow.

I would like to submit a pull request to fix however I'd appreciate your guidance on whether it's acceptable to have either a nil or made-up string value in a `Whois::Record::Registar` object.

Cheers

**Comment by weppos** [comment]
All `Registrar` fields are optional. If there is no ID anymore, I think it's reasonable to rely on the `Registrar Name` as a checkpoint and simply return the values we have.

Thanks for the report @afoster
