### ISSUE TITLE
whois.verisign-grs.com.rb Changed output...

### ISSUE THREAD

**Issue by bschrock** [weppos/whois-parser#56]
Our whois records are no longer getting parsed correctly, but when changing expires_on to the following it starts to work again.

node("Registry Expiry Date") { |value| parse_time(value) } 

Our example record is here.

   Domain Name: MANTA.COM
   Registry Domain ID: 109571704_DOMAIN_COM-VRSN
   Registrar WHOIS Server: whois.advancedregistrar.com
   Registrar URL: http://www.netearthone.com
   Updated Date: 2017-01-03T13:06:38Z
   Creation Date: 2004-01-08T19:49:14Z
   **Registry Expiry Date**: 2018-01-08T19:49:14Z
   Registrar: NetEarth One Inc. d/b/a NetEarth
   Registrar IANA ID: 1005
   Registrar Abuse Contact Email: a-b-u-s-e.whois.field@netearthone.com
   Registrar Abuse Contact Phone: +440.2030269987
   Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
   Name Server: NS-101.AWSDNS-12.COM
   Name Server: NS-1389.AWSDNS-45.ORG
   Name Server: NS-1950.AWSDNS-51.CO.UK
   Name Server: NS-759.AWSDNS-30.NET
   DNSSEC: unsigned
   URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/

**Comment by weppos** [comment]
Fixed in #57
