### ISSUE TITLE
Question on a few methods

### ISSUE THREAD

**Issue by xaoseric** [weppos/whois-parser#91]
Hi,
@weppos do you happen to know whats up with the :referral_whois and :referral_url methods? Also, the status method doesn't return a list of the domain statuses such as clientDeleteProhibited, perhaps another method for getting those could work? Also, is there any way to show the raw whois using the parser?

**Comment by weppos** [comment]
> do you happen to know whats up with the :referral_whois and :referral_url methods?

What do you mean?

> Also, the status method doesn't return a list of the domain statuses such as clientDeleteProhibited, perhaps another method for getting those could work?

Sadly, this is a very old issue https://github.com/weppos/whois/issues/5
Status should likely be replaced to return a struct object, containing both the list of statuses and the interpretation.

> Also, is there any way to show the raw whois using the parser?

That is in the record. You instantiate the parser from a whois record. Hence you have access to that record before you create the parser.

**Comment by thomas07vt** [comment]
```ruby
record = Whois.whois('google.com')
record.class
#=> Whois::Record
# To get the raw string, you can call to_s on the record
puts record.to_s
#=> Domain Name: GOOGLE.COM
#=> ...
#=> ...
#=> ...
```

**Comment by xaoseric** [comment]
The parser.rb file has the following commented out, but it appears to be implemented for some whois servers.
```
# :referral_whois, :referral_url,
```

**Comment by weppos** [comment]
Those methods make sense only for thin whois. Essentially, only .NET and .COM. I originally considered adding them as methods, but I then did not do it on purpose.

I can probably remove the commends.
