### ISSUE TITLE
All .io domains don't seem to parse

### ISSUE THREAD

**Issue by dgavey** [weppos/whois-parser#92]
I'm using the latest version of whois-parser and whois, the raw record is returned but the parser data seems to empty for everything.  

Before I look into it further I wanted to see if this is the case for others as well or if it's just a local issue.

**Comment by dgavey** [comment]
It looks like .io whois is returning as BaseIcannCompliant now.

**Comment by dgavey** [comment]
Looks like it's pretty close to BaseIcann except the Expiry Date has a different title.  Working on a PR and the tests.

**Comment by weppos** [comment]
.IO moved under Afilias system, hence they are using an Afilias-alike response. I also assume Afilias changed lately to have their system inline with ICANN requirements (which probably also make the `base_afilias` parsers obsolete).

**Comment by eheydrick** [comment]
Looks like #94 addresses this. Would love to see that merged and released.

**Comment by weppos** [comment]
Closed by https://github.com/weppos/whois-parser/commit/85c956c1b766cf3389e8f8f997c11ee0ae92414e
