### ISSUE TITLE
.org domain parsing fails with "error!': Unexpected token"

### ISSUE THREAD

**Issue by peterhoeg** [weppos/whois-parser#97]
Example code:

```ruby
#!/usr/bin/env ruby

require 'bundler/setup'
require 'whois'
require 'whois-parser'

whois = Whois.whois('example.org')
puts whois.parser.created_on
```

**Comment by talarini** [comment]
I've just created an PR fixing this issue
PR https://github.com/weppos/whois-parser/pull/98

Just a correction in regex to allow more than one \n on disclaimer's text

**Comment by talarini** [comment]
@weppos Hey, can you please merge the Pull Requests? There's a lot of domain parse broken but already fixed on others Pull Request sent months ago
